### ISSUE TITLE
Allow for promises

### ISSUE THREAD

**Issue by danwkennedy** [silas/node-consul#21]
It would be awesome if this module provided support for promises. Right now, we're wrapping our calls in Bluebird but with ES6 gaining ground, it would be nice to follow the standard.

**Comment by a-s-o** [comment]
+1; if you do consider using Bluebird for the promise implementation, along with its many benefits there is a helper method for this use case. See [nodeify](https://github.com/petkaantonov/bluebird/blob/2.x/API.md#nodeifyfunction-callback--object-options---promise)

Excerpt:

[nodeify ] returns back this promise instead of creating a new one. If the `callback` argument is not a function, this method does not do anything.

This can be used to create APIs that both accept node-style callbacks and return promises:

```js
function getDataFor(input, callback) {
    return dataFromDataBase(input).nodeify(callback);
}
```

**Comment by jewelsjacobs** [comment]
+1

**Comment by silas** [comment]
I'm going to follow whatever interface the node.js standard library uses, but I added a [helper function](https://github.com/silas/node-consul#promisify) for wrapping `consul` (assuming your library of choice doesn't automagically do it for you).

npm `>= 0.21.0`
