### ISSUE TITLE
Local port exhaustion (ENOBUFS)

### ISSUE THREAD

**Issue by AmazingTurtle** [silas/node-consul#68]
The problem is in conflict with the https://github.com/silas/node-papi repository.
The issues occurs when running multiple health checks to consul with a delay.

For health check, use consul.agent.check.pass({id:  ...}).
A new http client instance is created for each request against consul, which exhausts local ports and results in a ENOBUFS execption after a while.

**Comment by silas** [comment]
By default papi uses the default http/https transport, which doesn't open a new connection per request or create multiple clients. Unless you're doing something very strange that shouldn't be an issue. `ENOBUFS` can also mean you were out of memory.

It's been a while since you opened this request, have you continued to see this issue? What was the memory usage on the box when it occurred?

I used papi in an environment that was continuously doing 100+ req/s, so I don't think it's that. If you're still seeing this issue please re-open with additional details, but there isn't much I can do to fix this without more information or even better a reproducible test.
